Repository openghg/openghg, pull requests merged in 2021-07, with the labels that each got.

#91 Adding basic calculation of modelled mole fraction
  notebooks/tutorials/beginner_workflow/footprint_workflow.ipynb
  notebooks/tutorials/data/emissions/ch4-anthro_EUROPE_2012.nc
  openghg/processing/_process_footprint.py
Labels: high-priority

#93 Jinja fix for documentation build
  notebooks/tutorials/beginner_workflow/footprint_workflow.ipynb
  requirements-dev.txt
Labels: bugfix

#89 Update to NOAA module to retain "units" attributes
  openghg/modules/_noaa.py
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#88 Add basic Eulerian model class
  openghg/modules/__init__.py
  openghg/modules/_datasource.py
  openghg/modules/_eulerian_model.py
  openghg/processing/_search.py
  tests/data/eulerian_model/GEOSChem.SpeciesConc.20150101_0000z_reduced.nc4
  tests/modules/test_eulerian_model.py
Labels: high-priority, question

#70 Updated resampling when combining footprints and obs data
  openghg/processing/_observations.py
  openghg/processing/_process_footprint.py
  tests/helpers/__init__.py
  tests/helpers/helpers.py
Labels: enhancement

#95 Removing interface module
  openghg/interface/__init__.py
  openghg/interface/_credentials.py
  openghg/interface/_interface.py
  openghg/interface/_parse.py
  openghg/interface/_search.py
  openghg/interface/_upload.py
Labels: enhancement

#97 Removing ICOS processing functionality
  openghg/modules/__init__.py
  openghg/modules/_icos.py
  openghg/modules/_obs_surface.py
  openghg/processing/_enums.py
  tests/modules/test_icos.py
  tests/modules/test_obssurface.py
Labels: tidy

#96 Add type checking with mypy
  .github/workflows/main.yaml
  doc/source/development/fn_setup.rst
  mypy.ini
  openghg/__init__.py
  openghg/_version.py
  openghg/client/_jobrunner.py
  openghg/client/_process.py
  openghg/client/_rank_sources.py
  openghg/client/_retrieve.py
  openghg/client/_search.py
  openghg/client/_test_service.py
  openghg/dataobjects/_basedata.py
  openghg/dataobjects/_footprint_data.py
  openghg/dataobjects/_obsdata.py
  openghg/dataobjects/_searchresults.py
  openghg/jobs/_create.py
  openghg/jobs/_jobdrive.py
  openghg/jobs/_run.py
  openghg/jobs/_sshconnect.py
  openghg/localclient/_observations.py
  openghg/localclient/_process.py
  openghg/localclient/_rank_sources.py
  openghg/localclient/_search.py
  openghg/modules/_base.py
  openghg/modules/_beaco2n.py
  openghg/modules/_btt.py
  openghg/modules/_cranfield.py
  openghg/modules/_crds.py
  openghg/modules/_datasource.py
  openghg/modules/_ecmwf.py
  openghg/modules/_emissions.py
  openghg/modules/_eulerian_model.py
  openghg/modules/_eurocom.py
  openghg/modules/_footprints.py
  openghg/modules/_gcwerks.py
  openghg/modules/_metstore.py
  openghg/modules/_noaa.py
  openghg/modules/_npl.py
  openghg/modules/_obs_surface.py
  openghg/modules/_template.py
  openghg/modules/_thamesbarrier.py
  openghg/objectstore/__init__.py
  openghg/objectstore/_hugs_objstore.py
  openghg/objectstore/_local_store.py
  openghg/processing/_attributes.py
  openghg/processing/_export.py
  openghg/processing/_observations.py
  openghg/processing/_process_footprint.py
  openghg/processing/_search.py
  openghg/processing/_segment.py
  openghg/util/__init__.py
  openghg/util/_compliance.py
  openghg/util/_strings.py
  openghg/util/_time.py
  openghg/util/_util.py
  requirements-dev.txt
  requirements.txt
  tests/conftest.py
  tests/modules/test_datasource.py
  tests/processing/test_segment.py
Labels: enhancement
