Repository openghg/openghg, pull requests merged in 2021-03, with the labels that each got.

#25 Get obs refactor
  openghg/dataobjects/__init__.py
  openghg/dataobjects/_basedata.py
  openghg/dataobjects/_footprint_data.py
  openghg/dataobjects/_obsdata.py
  openghg/localclient/__init__.py
  openghg/localclient/_get_observations.py
  openghg/localclient/_obs_dataclass.py
  openghg/localclient/_search.py
  openghg/modules/_crds.py
  openghg/modules/_datasource.py
  openghg/processing/__init__.py
  openghg/processing/_attributes.py
  openghg/processing/_observations.py
  openghg/processing/_process_footprint.py
  openghg/processing/_recombination.py
  openghg/processing/_search.py
  openghg/processing/_segment.py
  openghg/util/_util.py
  requirements.txt
Labels: enhancement

#26 Added very basic read of emissions data
  openghg/modules/__init__.py
  openghg/modules/_datasource.py
  openghg/modules/_emissions.py
  openghg/processing/_process_footprint.py
  openghg/processing/_segment.py
Labels: enhancement

#40 Bug fixes in get_observations
  openghg/processing/_observations.py
  openghg/processing/_search.py
Labels: bugfix, enhancement

#41 Bring in the changes to fix species label mismtch
  openghg/processing/_attributes.py
  openghg/processing/_observations.py
  openghg/util/__init__.py
  openghg/util/_strings.py
  requirements.txt
  tests/localclient/test_get_observations.py
  tests/processing/test_observations.py
Labels: bugfix
