Repository openghg/openghg, pull requests merged in 2021-04, with the labels that each got.

#47 New way to lookup Datasources
  openghg/localclient/_rank_sources.py
  openghg/localclient/_search.py
  openghg/modules/_base.py
  openghg/modules/_beaco2n.py
  openghg/modules/_btt.py
  openghg/modules/_cranfield.py
  openghg/modules/_crds.py
  openghg/modules/_datasource.py
  openghg/modules/_footprints.py
  openghg/modules/_gcwerks.py
  openghg/modules/_icos.py
  openghg/modules/_metstore.py
  openghg/modules/_noaa.py
  openghg/modules/_npl.py
  openghg/modules/_obs_surface.py
  openghg/modules/_thamesbarrier.py
  openghg/processing/_attributes.py
  openghg/processing/_observations.py
  openghg/processing/_search.py
  openghg/processing/_segment.py
  openghg/util/__init__.py
  openghg/util/_compliance.py
  openghg/util/_strings.py
  openghg/util/_util.py
  tests/data/proc_test_data/CRDS/bsd.picarro.1minute.248m.dat
  tests/data/proc_test_data/CRDS/bsd.picarro.1minute.248m.future.dat
  tests/data/proc_test_data/GC/capegrim-medusa.18.precisions.C
  tests/data/proc_test_data/GC/capegrim-medusa.future.C
  tests/data/proc_test_data/GC/capegrim-medusa.future.precisions.C
  tests/localclient/test_get_surface_obs.py
  tests/localclient/test_local_process.py
  tests/localclient/test_local_ranking.py
  tests/localclient/test_local_search.py
  tests/modules/test_beaco2n.py
  tests/modules/test_cranfield.py
  tests/modules/test_datasource.py
  tests/modules/test_footprints.py
  tests/modules/test_gcwerks.py
  tests/modules/test_metstore.py
  tests/modules/test_noaa.py
  tests/modules/test_obssurface.py
  tests/processing/test_recombination.py
  tests/processing/test_search.py
Labels: bugfix

#48 Update the search function and add in Datasource lookup
  notebooks/interface/visualise_ranking.ipynb
  notebooks/tutorials/beginner_workflow/workflow.ipynb
  openghg/localclient/__init__.py
  openghg/localclient/_observations.py
  openghg/localclient/_rank_sources.py
  openghg/localclient/_search.py
  openghg/modules/_base.py
  openghg/modules/_beaco2n.py
  openghg/modules/_btt.py
  openghg/modules/_cranfield.py
  openghg/modules/_crds.py
  openghg/modules/_datasource.py
  openghg/modules/_footprints.py
  openghg/modules/_gcwerks.py
  openghg/modules/_icos.py
  openghg/modules/_metstore.py
  openghg/modules/_noaa.py
  openghg/modules/_npl.py
  openghg/modules/_obs_surface.py
  openghg/modules/_thamesbarrier.py
  openghg/processing/__init__.py
  openghg/processing/_attributes.py
  openghg/processing/_observations.py
  openghg/processing/_recombination.py
  openghg/processing/_search.py
  openghg/processing/_segment.py
  openghg/util/__init__.py
  openghg/util/_compliance.py
  openghg/util/_strings.py
  openghg/util/_util.py
  requirements.txt
  tests/data/proc_test_data/CRDS/bsd.picarro.1minute.248m.dat
  tests/data/proc_test_data/CRDS/bsd.picarro.1minute.248m.future.dat
  tests/data/proc_test_data/CRDS/hfd.picarro.1minute.100m.min.dat
  tests/data/proc_test_data/GC/capegrim-medusa.18.precisions.C
  tests/data/proc_test_data/GC/capegrim-medusa.future.C
  tests/data/proc_test_data/GC/capegrim-medusa.future.precisions.C
  tests/localclient/test_get_observations.py
  tests/localclient/test_get_surface_obs.py
  tests/localclient/test_local_process.py
  tests/localclient/test_local_ranking.py
  tests/localclient/test_local_search.py
  tests/modules/test_beaco2n.py
  tests/modules/test_cranfield.py
  tests/modules/test_datasource.py
  tests/modules/test_footprints.py
  tests/modules/test_gcwerks.py
  tests/modules/test_metstore.py
  tests/modules/test_noaa.py
  tests/modules/test_obssurface.py
  tests/processing/test_observations.py
  tests/processing/test_recombination.py
  tests/processing/test_search.py
Labels: bugfix, enhancement

#51 Moving code into BaseModule class
  openghg/modules/_base.py
  openghg/modules/_emissions.py
  openghg/modules/_footprints.py
  openghg/modules/_metstore.py
  openghg/modules/_obs_surface.py
  tests/modules/test_obssurface.py
Labels: enhancement

#52 Add in NOAA ObsPack read
  openghg/modules/_beaco2n.py
  openghg/modules/_btt.py
  openghg/modules/_cranfield.py
  openghg/modules/_crds.py
  openghg/modules/_eurocom.py
  openghg/modules/_gcwerks.py
  openghg/modules/_icos.py
  openghg/modules/_noaa.py
  openghg/modules/_npl.py
  openghg/modules/_obs_surface.py
  openghg/modules/_thamesbarrier.py
  openghg/processing/_recombination.py
  tests/data/proc_test_data/NOAA/ch4_esp_surface-flask_2_representative.nc
  tests/localclient/test_get_surface_obs.py
  tests/modules/test_noaa.py
  tests/modules/test_obssurface.py
  tests/processing/test_search.py
Labels: enhancement

#54 Inlet labels now used instead of labels read directly from data
  openghg/modules/_gcwerks.py
  openghg/processing/_recombination.py
  tests/localclient/test_get_surface_obs.py
  tests/mock/hugs/test_process.py
  tests/modules/test_gcwerks.py
  tests/modules/test_obssurface.py
  tests/processing/test_recombination.py
  tests/processing/test_search.py
Labels: enhancement

#56 Adding in Datasource lookup to footprint and emissions objects
  openghg/modules/_base.py
  openghg/modules/_datasource.py
  openghg/modules/_emissions.py
  openghg/modules/_footprints.py
  openghg/modules/_obs_surface.py
  openghg/processing/_search.py
  openghg/processing/_segment.py
  openghg/util/_util.py
  tests/data/emissions/co2-gpp-cardamom-mth_EUROPE_2012.nc
  tests/modules/test_datasource.py
  tests/modules/test_emissions.py
  tests/modules/test_footprints.py
Labels: enhancement

#61 Fix GCWERKS data files with unrecognized inlets not being read correctly
  openghg/data/process_gcwerks_parameters.json
  openghg/modules/_gcwerks.py
  tests/data/proc_test_data/GC/capegrim-medusa.18.C
  tests/data/proc_test_data/GC/ridgehill-md.11.C
  tests/data/proc_test_data/GC/ridgehill-md.11.precisions.C
  tests/data/proc_test_data/GC/shangdianzi-medusa.18.C
  tests/data/proc_test_data/GC/shangdianzi-medusa.18.precisions.C
  tests/data/proc_test_data/GC/trinidadhead-window-inlet.01.C
  tests/data/proc_test_data/GC/trinidadhead.01.precisions.C
  tests/modules/test_gcwerks.py
Labels: bugfix

#55 Adding Python 3.9 GitHub actions runner
  .github/workflows/main.yaml
Labels: enhancement

#62 Fix for UUID error due to incorrect inlet in metadata
  openghg/data/process_gcwerks_parameters.json
  openghg/modules/_gcwerks.py
  openghg/modules/_obs_surface.py
  openghg/processing/_segment.py
  tests/data/proc_test_data/GC/capegrim-medusa.18.C
  tests/data/proc_test_data/GC/ridgehill-md.11.C
  tests/data/proc_test_data/GC/ridgehill-md.11.precisions.C
  tests/data/proc_test_data/GC/shangdianzi-medusa.18.C
  tests/data/proc_test_data/GC/shangdianzi-medusa.18.precisions.C
  tests/data/proc_test_data/GC/trinidadhead-window-inlet.01.C
  tests/data/proc_test_data/GC/trinidadhead.01.precisions.C
  tests/modules/test_gcwerks.py
  tests/modules/test_obssurface.py
Labels: bugfix

#65 Updating the GitHub actions workflow to check CodeCov SHAs and commit hash of action
  .github/workflows/main.yaml
Labels: enhancement

#63 Adding sampling period to metadata and attributes
  openghg/modules/_crds.py
  openghg/modules/_gcwerks.py
  openghg/processing/_attributes.py
  tests/localclient/test_get_surface_obs.py
  tests/modules/test_crds.py
  tests/modules/test_datasource.py
  tests/modules/test_gcwerks.py
  tests/modules/test_obssurface.py
  tests/processing/test_attributes.py
  tests/processing/test_search.py
Labels: enhancement

#53 Adding checking for metadata passed in by user and read from filename
  openghg/data/process_gcwerks_parameters.json
  openghg/modules/_crds.py
  openghg/modules/_gcwerks.py
  openghg/modules/_obs_surface.py
  openghg/util/_util.py
  tests/data/proc_test_data/GC/trinidadhead.01.window-inlet.C
  tests/localclient/test_local_process.py
  tests/modules/test_crds.py
  tests/modules/test_gcwerks.py
  tests/modules/test_obssurface.py
  tests/processing/test_attributes.py
Labels: enhancement
