Repository openghg/openghg, pull requests merged in 2023-08, with the labels that each got.

#696 432 update searchresults for pretty console output
  CHANGELOG.md
  environment.yaml
  mypy.ini
  openghg/dataobjects/_searchresults.py
  requirements.txt
Labels: enhancement

#741 Fix for bucket being saved to JSON
  CHANGELOG.md
  openghg/store/base/_base.py
  tests/conftest.py
  tests/store/test_obssurface.py
Labels: bugfix

#744 Add openghg conda channel
  .github/workflows/workflow.yaml
Labels: bugfix

#746 0.6.2 release
  .github/workflows/workflow.yaml
  CHANGELOG.md
  openghg/store/base/_base.py
  tests/conftest.py
  tests/store/test_obssurface.py
Labels: release

#763 Enable read-only opening of metastore
  CHANGELOG.md
  openghg/retrieve/_search.py
  openghg/store/_metadata.py
  openghg/types/__init__.py
  openghg/types/_errors.py
  tests/store/test_metastore.py
Labels: enhancement, storage-and-metadata
