Repository openghg/openghg, pull requests merged in 2023-12, with the labels that each got.

#844 Iss547-Adding object store explanation
  doc/source/tutorials/local/Adding_new_data/Adding_observation_data.rst
Labels: documentation, high-priority

#847 Add extra notes about `DataManager` usage.
  doc/source/tutorials/local/Managing_object_store/Modifying_and_deleting_data.rst
  openghg/dataobjects/_datamanager.py
Labels: documentation

#804 Iss797 parse intem emissions
  CHANGELOG.md
  doc/source/api/devapi_standardise.rst
  openghg/standardise/_standardise.py
  openghg/standardise/emissions/__init__.py
  openghg/standardise/emissions/_intem.py
  openghg/store/_emissions.py
  openghg/types/_enum.py
  tests/data/emissions/ch4_intem.nc
  tests/standardise/emissions/test_intem.py
  tests/standardise/test_standardise.py
  tests/store/test_emissions.py
Labels: enhancement, high-priority, new feature

#806 Adding new filter for ObsPack data retrieval from ICOS Carbon Portal
  CHANGELOG.md
  openghg/retrieve/icos/_retrieve.py
  tests/data/retrieve/df_0.csv.bz2
  tests/data/retrieve/df_1.csv.bz2
  tests/data/retrieve/dobj0.pkl.bz2
  tests/data/retrieve/dobj1.pkl.bz2
  tests/data/retrieve/dobj2.pkl.bz2
  tests/data/retrieve/dobj3.pkl.bz2
  tests/data/retrieve/wao_pids.csv.bz2
  tests/retrieve/icos/test_retrieve_icos.py
Labels: high-priority

#816 Iss618 pandas 2.0 causes tests to fail
  CHANGELOG.md
  environment-dev.yaml
  environment.yaml
  openghg/standardise/surface/_eurocom.py
  openghg/standardise/surface/_gcwerks.py
  openghg/standardise/surface/_glasgow_licor.py
  openghg/standardise/surface/_icos.py
  openghg/standardise/surface/_noaa.py
  openghg/standardise/surface/_npl.py
  openghg/standardise/surface/_thamesbarrier.py
  requirements.txt
  tests/util/test_time.py
Labels: high-priority
