Repository openghg/openghg, pull requests merged in 2024-08, with the labels that each got.

#1084 Pin icoscp and fix tests based on current retrieval
  environment.yaml
  requirements.txt
  tests/retrieve/icos/test_retrieve_icos.py
Labels: icos_retrieve

#1094 Tidy up: allowing parser functions to be found using data_type input
  openghg/store/_flux.py
  openghg/store/_flux_timeseries.py
  openghg/store/_footprints.py
  openghg/store/_obscolumn.py
  openghg/store/_obssurface.py
  openghg/store/spec/__init__.py
  openghg/store/spec/_specification.py
Labels: tidy

#1095 Tidy up: centralise parser loader so this can be called by data_type
  openghg/standardise/footprints/__init__.py
  openghg/standardise/footprints/_acrg_org.py
  openghg/standardise/footprints/_paris.py
  openghg/store/_flux.py
  openghg/store/_flux_timeseries.py
  openghg/store/_footprints.py
  openghg/store/_obscolumn.py
  openghg/store/_obssurface.py
  openghg/util/__init__.py
  openghg/util/_file.py
  tests/standardise/footprints/test_acrg_org.py
  tests/standardise/footprints/test_paris.py
  tests/util/test_file.py
Labels: tidy

#1100 Making sure all file_hashes are added to the ObsSurface object
  CHANGELOG.md
  openghg/store/_obssurface.py
  tests/data/proc_test_data/OPENGHG/DECC-picarro_TAC_20130131_co2-185m-20220928.nc
  tests/data/proc_test_data/OPENGHG/DECC-picarro_TAC_20130131_co2-185m-20220929.nc
  tests/data/proc_test_data/OPENGHG/DECC-picarro_TAC_20130131_co2-185m-20220929_cut.nc
  tests/standardise/test_standardise.py
  tests/store/test_obssurface.py
Labels: bugfix

#1109 Tidy up: Split out sampling period check
  openghg/store/_obssurface.py
  openghg/util/__init__.py
  openghg/util/_time.py
  tests/retrieve/conftest.py
  tests/standardise/test_standardise.py
  tests/store/test_obssurface.py
Labels: tidy

#1108 Ensuring filepath values within BaseStore.check_hashes are set to Path type
  CHANGELOG.md
  openghg/store/base/_base.py
Labels: bugfix

#1101 Tidy naming of filepath in ObsSurface
  CHANGELOG.md
  openghg/standardise/surface/_agage.py
  openghg/standardise/surface/_aqmesh.py
  openghg/standardise/surface/_beaco2n.py
  openghg/standardise/surface/_btt.py
  openghg/standardise/surface/_cranfield.py
  openghg/standardise/surface/_crds.py
  openghg/standardise/surface/_eurocom.py
  openghg/standardise/surface/_gcwerks.py
  openghg/standardise/surface/_glasgow_picarro.py
  openghg/standardise/surface/_icos.py
  openghg/standardise/surface/_noaa.py
  openghg/standardise/surface/_npl.py
  openghg/standardise/surface/_openghg.py
  openghg/standardise/surface/_thamesbarrier.py
  openghg/store/_obssurface.py
  tests/standardise/surface/test_agage.py
  tests/standardise/surface/test_aqmesh.py
  tests/standardise/surface/test_beaco2n.py
  tests/standardise/surface/test_btt.py
  tests/standardise/surface/test_cranfield.py
  tests/standardise/surface/test_crds.py
  tests/standardise/surface/test_gcwerks.py
  tests/standardise/surface/test_icos.py
  tests/standardise/surface/test_noaa.py
  tests/standardise/surface/test_npl.py
  tests/standardise/surface/test_openghg_surface.py
  tests/standardise/surface/test_thamesbarrier.py
  tests/store/test_datasource.py
Labels: tidy

#1110 Tidy up: Update NOAA keywords
  CHANGELOG.md
  openghg/standardise/surface/_noaa.py
  tests/standardise/surface/test_noaa.py
Labels: tidy

#1029 Catch AttributeError if someone passes a bool
  CHANGELOG.md
  doc/source/tutorials/local/Exploring_data/Retrieving_remote_data.rst
  openghg/standardise/meta/_metadata.py
  tests/retrieve/icos/test_retrieve_icos.py
Labels: bugfix
