Repository openghg/openghg, pull requests merged in 2024-05, with the labels that each got.

#997 Fix to be able to retrieve non-sequential data
  CHANGELOG.md
  openghg/dataobjects/_basedata.py
  tests/retrieve/conftest.py
  tests/retrieve/test_access.py
Labels: bugfix

#999 Update `supplementary_data` to `openghg_defs`
  CHANGELOG.md
  openghg/standardise/_standardise.py
  openghg/standardise/meta/_attributes.py
  openghg/standardise/surface/_crds.py
  openghg/standardise/surface/_gcwerks.py
  openghg/standardise/surface/_icos.py
  openghg/standardise/surface/_noaa.py
  openghg/standardise/surface/_openghg.py
  openghg/standardise/surface/_thamesbarrier.py
  openghg/store/_obssurface.py
Labels: tidy

#984 Synonyms of species during standardisation
  CHANGELOG.md
  openghg/store/_boundary_conditions.py
  openghg/store/_flux.py
  openghg/store/_footprints.py
  openghg/store/_obscolumn.py
  openghg/store/_obssurface.py
  openghg/util/_species.py
  tests/data/footprints/MHD-10magl_UKV_hfo-1234zee_EUROPE_201401_test.nc
  tests/store/test_footprints.py
  tests/util/test_util.py
Labels: bugfix

#1021 Move to use tmp_path instead of tmpdir
  tests/util/test_user.py
Labels: bugfix

#1023 Docs tidy - 1 - quick tidy and update tutorials sidebar
  doc/source/conf.py
  doc/source/index.rst
  doc/source/install.rst
  doc/source/packaging.rst
  doc/source/tutorials/index.rst
  doc/source/tutorials/local/Managing_object_store/Managing_data.rst
Labels: documentation, tidy

#870 Class and parse_crf for 1D data
  CHANGELOG.md
  doc/source/api/api_standardise.rst
  doc/source/api/devapi_standardise.rst
  doc/source/api/devapi_store.rst
  doc/source/tutorials/local/Adding_data/Adding_ancillary_data.rst
  environment-dev.yaml
  environment.yaml
  openghg/standardise/__init__.py
  openghg/standardise/_standardise.py
  openghg/standardise/flux_timeseries/__init__.py
  openghg/standardise/flux_timeseries/_crf.py
  openghg/store/__init__.py
  openghg/store/_flux_timeseries.py
  openghg/store/_meta.py
  openghg/store/base/_datasource.py
  openghg/store/spec/_specification.py
  openghg/types/__init__.py
  openghg/types/_enum.py
  openghg/util/__init__.py
  openghg/util/_file.py
  openghg/util/_time.py
  openghg/util/_util.py
  requirements.txt
  tests/data/flux_timeseries/GBR_2023_2021_13042023_170954.xlsx
  tests/helpers/__init__.py
  tests/helpers/helpers.py
  tests/standardise/test_standardise.py
Labels: new feature
