Repository openghg/openghg, pull requests merged in 2025-04, with the labels that each got.

#1291 Simplify ModelScenario alignment around platform
  openghg/analyse/_alignment.py
  openghg/analyse/_scenario.py
  openghg/types/__init__.py
  openghg/types/_types.py
Labels: tidy, refactor

#1292 Update combine_datasets function to use native xarray steps rather than numpy
  openghg/analyse/_alignment.py
Labels: tidy

#1316 Resolving documentation build failure
  CHANGELOG.md
  openghg/util/_combine.py
Labels: documentation

#1326 Created function to do intermediate baseline sensitivities calculation
  CHANGELOG.md
  openghg/analyse/_modelled_baseline.py
  openghg/analyse/_scenario.py
Labels: tidy, analysis
