Repository openghg/openghg, pull requests merged in 2025-06, with the labels that each got.

#1360 Units for mf similar to xch4
  CHANGELOG.md
  openghg/retrieve/_access.py
  tests/retrieve/test_access.py
Labels: bugfix

#1369 Fixing documentation to use `filepath` rather than previous `filepaths`
  doc/source/tutorials/local/Adding_data/Adding_observation_data.rst
Labels: documentation, bugfix

#1368 Updating the logging to use 'openghg' name directly rather than __name__
  openghg/__init__.py
Labels: logging
